### ISSUE TITLE
Read-only repos not updated?

### ISSUE THREAD

**Issue by Stefan-ST** [OAuth2-Framework/oauth2-framework#64]
| Q                    | A
| -------------------- | -----
| Project              | server-library, server-bundle, client-library
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | dev-master

It seems the read-only repositories with the libraries and bundles haven't been updated for a while despite there has been changes these components on this repo.

**Comment by Spomky** [comment]
Hi @Stefan-ST 

There are several reasons that explain this discrepancy between the main repository and sub repositories.

* It does not make sense for me to sync them as the main one is not stable enough. I am testing the framework against the [OIDC Certification tool](http://openid.net/certification/testing/) and some test do not pass.
* [spomky-labs/jose](https://github.com/Spomky-Labs/JOSE) will be deprecated by the end of the year. The [new project](https://github.com/web-token/jwt-framework) will replace it and some modifications have to be implemented.
* I will split the library server and create sub components.
* I haven't created the split tool for that project. I will copy the one I created for [the web-token project](https://github.com/web-token/splitter).

**Comment by Stefan-ST** [comment]
Hi,

thanks for the explanation. I'm looking forward to see your OIDC server implementation.
